spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
#  rabbitmq:
#    addresses: 127.0.0.1
#    port: 3306
#    username: root
#    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088

wx:
  appId:
  mchId:
  mchKey:
  notifyUrl: http://imooc-mall123.natapp1.cc/pay/notify
  returnUrl: localhost:8080
alipay:
  appId:
  privateKey:
  aliPayPublicKey:
  notifyUrl: http://imooc-mall123.natapp1.cc/pay/notify
  returnUrl: localhost:8080